apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: default
spec:
  defaultGeneratedCert:
    resolver: myresolver
    domain:
      main: altaif4.fr
      sans:
        - "*.altaif4.fr"