apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
  labels:
    app: prometheus
spec:
  storageClassName: manual
  capacity:
    storage: 20M
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/etc/prometheus"