apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-web-pv
  labels:
    app: nginx
spec:
  storageClassName: manual
  capacity:
    storage: 50M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/www/nginx-kube"