apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: nginx-web-storage
        persistentVolumeClaim:
          claimName: nginx-web-pv-claim
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
          name: nginx-port
        volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: nginx-web-storage
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-services
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - name: port-web
    protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-web-pv-claim
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50M