apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-persistent-volume-claim
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 8G
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-backup-pvc
  namespace: postgres
spec:
  storageClassName: "standard"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200M
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresdb
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres-container
          image: postgres
          ports:
          - containerPort: 5432
          envFrom:
          - configMapRef:
              name: pg-secret-credentials
          volumeMounts:
          - mountPath: /var/lib/postgres/data
            name: db-data
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: pg-persistent-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: pg-node-port
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
  - port: 5432
  selector:
    app: postgres