apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-pv
  labels:
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 8G
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/data/postgres"